log_dir: "Models/ThreeSpeaker"
first_stage_path: "first_stage.pth"
save_freq: 25
log_interval: 10
device: "cuda"
epochs_1st: 150 # Optimized for small dataset
epochs_2nd: 75 # Optimized for small dataset
batch_size: 8  # Reduced for memory efficiency
max_len: 200 # Reduced for memory efficiency
pretrained_model: ""
second_stage_load_pretrained: true
load_only_params: false

F0_path: "Utils/JDC/bst.t7"
ASR_config: "Utils/ASR/config.yml"
ASR_path: "Utils/ASR/epoch_00080.pth"
PLBERT_dir: 'Utils/PLBERT/'

data_params:
  train_data: "Data/train_list.txt"
  val_data: "Data/val_list.txt"
  root_path: "Data/wavs"
  OOD_data: "Data/OOD_texts.txt"
  min_length: 50

preprocess_params:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300

model_params:
  multispeaker: true

  dim_in: 64 
  hidden_dim: 512
  max_conv_dim: 512
  n_layer: 3
  n_mels: 80

  n_token: 178
  max_dur: 50
  style_dim: 128
  
  dropout: 0.2

  # config for decoder
  decoder: 
      type: 'istftnet'
      dim: 512
      resblock_kernel_sizes: [3, 7, 11]
      upsample_rates: [10, 6]
      upsample_initial_channel: 512
      resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
      upsample_kernel_sizes: [20, 12]
      gen_istft_n_fft: 20
      gen_istft_hop_size: 5
      
  # speech language model config
  slm:
      model: 'microsoft/wavlm-base-plus'
      sr: 16000
      hidden: 768
      nlayers: 13
      initial_channel: 64
  
  # style diffusion model config
  diffusion:
    embedding_mask_proba: 0.1
    # transformer config
    transformer:
        num_layers: 3
        num_heads: 8
        head_features: 64
        multiplier: 2

    # diffusion distribution config
    dist:
        sigma_data: 0.2
        estimate_sigma_data: true
        mean: -3.0
        std: 1.0
  
loss_params:
    lambda_mel: 5.
    lambda_gen: 1.
    lambda_slm: 1.
    
    lambda_mono: 1.
    lambda_s2s: 1.
    TMA_epoch: 5

    lambda_F0: 1.
    lambda_norm: 1.
    lambda_dur: 1.
    lambda_ce: 20.
    lambda_sty: 1.
    lambda_diff: 1.
    
    diff_epoch: 30  # Start later for small dataset
    joint_epoch: 50  # Start later for small dataset

optimizer_params:
    lr: 1e-4
    eps: 1e-6
    weight_decay: 1e-4
    grad_norm: 1.0

slmadv_params:
    min_len: 300
    max_len: 400
    batch_percentage: 0.5
    
use_gt_dur: false
use_gt_f0: false
add_blank: true