log_dir: "Models/ThreeSpeaker"
first_stage_path: "first_stage.pth"
save_freq: 20  # Save every 20 epochs
log_interval: 10
device: "cuda"
epochs_1st: 250  # Optimal for small dataset with augmentation (community-tested)
epochs_2nd: 150  # Extended for stage 2
batch_size: 16   # MUST be >= 16 to avoid NaN
max_len: 100    # Optimized for memory
pretrained_model: ""  # Start fresh
second_stage_load_pretrained: false
load_only_params: false

F0_path: "Utils/JDC/bst.t7"
ASR_config: "Utils/ASR/config.yml"
ASR_path: "Utils/ASR/epoch_00080.pth"
PLBERT_dir: 'Utils/PLBERT/'

data_params:
  train_data: "Data/train_list_augmented.txt"  # Use augmented data
  val_data: "Data/val_list_augmented.txt"      # Use augmented validation
  root_path: "Data/wavs"
  OOD_data: "Data/OOD_texts.txt"
  min_length: 50

preprocess_params:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300

model_params:
  multispeaker: true
  
  dim_in: 64 
  hidden_dim: 512
  max_conv_dim: 512
  n_layer: 3
  n_mels: 80
  
  n_token: 178
  max_dur: 50
  style_dim: 128
  
  dropout: 0.25  # Slightly increased for augmented data
  
  decoder: 
      type: 'hifigan'
      resblock_kernel_sizes: [3,7,11]
      upsample_rates: [10,5,3,2]
      upsample_initial_channel: 512
      resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
      upsample_kernel_sizes: [20,10,6,4]
  
  slm:
      model: 'microsoft/wavlm-base-plus'
      sr: 16000
      hidden: 768
      nlayers: 13
      initial_channel: 64
  
  diffusion:
    embedding_mask_proba: 0.1
    transformer:
      num_layers: 3
      num_heads: 8
      head_features: 64
      multiplier: 2
    
    dist:
      sigma_data: 0.2
      estimate_sigma_data: true
      mean: -3.0
      std: 1.0

loss_params:
    lambda_mel: 5.
    lambda_gen: 1.
    lambda_slm: 1.
    
    lambda_mono: 1.
    lambda_s2s: 1.
    TMA_epoch: 10  # Delayed slightly for augmented data
    
    lambda_F0: 1.
    lambda_norm: 1.
    lambda_dur: 1.
    lambda_ce: 8.   # Slightly reduced for stability
    lambda_sty: 1.
    lambda_diff: 1.
    
    diff_epoch: 30   # Delayed for stability
    joint_epoch: 40  # Delayed for stability

# Optimized learning rates for augmented data
optimizer_params:
  lr: 0.00008      # Slightly lower for stability
  bert_lr: 0.000008
  ft_lr: 0.000008

slmadv_params:
  min_len: 80     # Reduced for memory
  max_len: 120    # Reduced for memory
  batch_percentage: 0.15  # Further reduced
  iter: 20
  thresh: 5
  scale: 0.01
  sig: 1.5