log_dir: "Models/ThreeSpeaker"
first_stage_path: "first_stage.pth"
save_freq: 10
log_interval: 10
device: "cuda"
epochs_1st: 300 # Increased epochs for small dataset
epochs_2nd: 150 # Increased epochs for small dataset
batch_size: 16  # Can use larger batch with shorter clips
max_len: 400  # 400 frames = ~5 seconds (clips are 15 seconds, plenty of room)
pretrained_model: ""
second_stage_load_pretrained: true # set to true if the pre-trained model is for 2nd stage
load_only_params: false # set to true if do not want to load epoch numbers and optimizer parameters

F0_path: "Utils/JDC/bst.t7"
ASR_config: "Utils/ASR/config.yml"
ASR_path: "Utils/ASR/epoch_00080.pth"
PLBERT_dir: 'Utils/PLBERT/'

data_params:
  train_data: "Data/train_list.txt"
  val_data: "Data/val_list.txt"
  root_path: "Data/wavs"  # Root directory for audio files
  OOD_data: "Data/OOD_texts.txt"
  min_length: 50 # sample until texts with this size are obtained for OOD texts

preprocess_params:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300

model_params:
  multispeaker: true  # IMPORTANT: Set to true for multi-speaker training

  dim_in: 64 
  hidden_dim: 512
  max_conv_dim: 512
  n_layer: 3
  n_mels: 80

  n_token: 178 # number of phoneme tokens
  max_dur: 50 # maximum duration of a single phoneme
  style_dim: 128 # style vector size
  
  dropout: 0.2

  # config for decoder
  decoder: 
      type: 'istftnet' # either hifigan or istftnet
      dim: 512
      resblock_kernel_sizes: [3, 7, 11]
      upsample_rates: [10, 6]
      upsample_initial_channel: 512
      resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
      upsample_kernel_sizes: [20, 12]
      gen_istft_n_fft: 20
      gen_istft_hop_size: 5

  # config for text aligner
  text_aligner:
    hidden_dim: 256
    n_layer: 3
    
  # config for prosody predictor
  prosody_predictor:
    style_dim: 128
    hidden_dim: 256
    n_layer: 3

  # config for diffusion model
  diffusion:
    embedding_mask_proba: 0.1
    # transformer config
    transformer:
        num_layers: 3
        num_heads: 8
        hidden_dim: 256
        ffn_dim: 1024
        dropout: 0.1

  # config for adv training
  batch_percentage: 0.3  # Reduced to prevent OOM during SLM adversarial training
  
slmadv_params:
  min_len: 400 # minimum length of samples
  max_len: 500 # maximum length of samples  
  batch_percentage: 0.3 # percentage of SLM adversarial training batch size
  iter: 10 # update the discriminator every this iterations of G

optimizer:
  learning_rate: 1e-4
  eps: 1e-8
  beta1: 0.9
  beta2: 0.999
  warmup_steps: 200

scheduler_params:
  gamma: 0.999875

loss_params:
  lambda_mel: 5.
  lambda_kl: 0.1
  lambda_kl_dur: 0.1
  lambda_ce: 1.
  lambda_norm: 1.
  lambda_f0: 1.
  lambda_gen: 1.
  lambda_slm: 1.

joint_epoch: 50  # Start SLM adversarial training after this epoch in second stage